### ISSUE TITLE
DiscrimFarmer stopped at the wrong discriminator

### ISSUE THREAD

**Issue by ghost** [ducc/DiscrimFarmer#8]
It stopped at '6666' even though this discriminator wasn't on my list. My list was: 0666,9999,0420,0001,7777,6699,1999,0013,0015,0019 .
Here's a screenshot:
![error](https://user-images.githubusercontent.com/24621065/27002294-98c257ec-4dde-11e7-9336-70d83409caa8.png)

**Comment by ducc** [comment]
https://github.com/ducc/DiscrimFarmer/blob/master/main.go#L38-L43

**Comment by ghost** [comment]
I see, thank you.
