### ISSUE TITLE
401 Unauthorized?

### ISSUE THREAD

**Issue by outpoints** [ducc/DiscrimFarmer#9]
`INFO[0000] Starting...
FATA[0000] Error getting user details                    error="HTTP 401 Unauthorized, {"code": 0, "message": "401: Unauthorized"}"
`
What do I do?
Did they patch it?

**Comment by ducc** [comment]
has this only just started happening?

**Comment by outpoints** [comment]
It worked for me to get #0001, I'm trying to help a friend out and this happened so I couldn't even use it once

**Comment by ducc** [comment]
probably an issue with the token or password, definitely not an issue with this program
